version: 2

updates:
  - package-ecosystem: "npm"
    directories: ["/web", "/api"]
    schedule:
      interval: "weekly"
    groups:
      security-updates:
        applies-to: "security-updates"
        dependency-type: "production"
      patch-minor-updates:
        update-types: ["minor", "patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
