# To learn about this file, please see https://www.gitpod.io/docs/references/gitpod-yml

image: gitpod/workspace-postgres

tasks:
  - init: |
      # Cleanup terminal
      printf "\033[3J\033c\033[3J"

      # install dependencies
      nvm install 20.12.2
      corepack enable
      corepack install
      yarn install

      # setup auth
      SESSION_SECRET=$(yarn rw g secret | sed -n '2p' | sed 's/^[ \t]*//;s/[ \t]*$//')
      echo "SESSION_SECRET=$SESSION_SECRET" >> .env

      # setup db
      yarn rw prisma migrate dev

    command: |
      corepack enable
      corepack install
      yarn rw dev

ports:
  - port: 5432
    name: PostgreSQL database
    onOpen: ignore
  - port: 8910
    name: RedwoodJS web application
    onOpen: notify # because we already have [browser].open = true in redwood.toml
  - port: 8911
    name: Serverless functions
    onOpen: ignore

vscode:
  extensions:
    - "dbaeumer.vscode-eslint"
    - "eamodio.gitlens"
    # - "ofhumanbondage.react-proptypes-intellisense" - Not published to Open VSX (yet)
    - "mgmcdermott.vscode-language-babel"
    - "wix.vscode-import-cost"
    - "pflannery.vscode-versionlens"
    - "editorconfig.editorconfig"
    - "prisma.prisma"
    - "graphql.vscode-graphql"
    - graphql.vscode-graphql-syntax
