name: Redwood CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
  TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

jobs:
  # Reusable step for installing dependencies
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
      - run: corepack enable
      - run: yarn install

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run linter
        run: yarn rw lint

  build:
    runs-on: ubuntu-latest
    needs: setup
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Build Redwood app
        run: yarn rw build
      - name: Run API tests
        run: yarn rw test api --no-watch
      - name: Run Web tests
        run: yarn rw test web --no-watch
